# Generated by Django 5.1.4 on 2024-12-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
